languageCode = "en-us"
theme = "hugo-blog-awesome"
publishDir = "docs"
canonifyURLs = false
relativeURLs = true
title = "michaelmackinnon.io"
slogan = "Security Engineering Notes"

[params.assets]
css = ["css/custom.css"]

[params.nav]
showCategories = true
showTags = false

[[params.nav.custom]]
title = "About"
url = "/about"

[Languages.en-gb.params]
  defaultColor = "dark" # set color mode: dark, light, auto
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/post/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Security Engineering"
  name = "Michael MacKinnon"
  description = "I build and harden backend systems, focusing on real-world failure and security."

[[params.socialIcons]]
name = "github"
url = "https://github.com/mike-mack"

[[params.socialIcons]]
name = "linkedin"
url = "www.linkedin.com/in/mjmackinnon"