baseURL = ""
languageCode = "en-us"
title = "Mike MacKinnon"
theme = "tale"
publishDir = "docs"
paginate = 2

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0