languageCode = "en-us"
theme = "hugo-blog-awesome"
publishDir = "docs"
canonifyURLs = false
relativeURLs = true
title = ""
slogan = ""

[params.assets]
css = ["css/custom.css"]

[params.nav]
showCategories = true
showTags = false

[[params.nav.custom]]
title = "About"
url = "/about"